# Generated by Django 3.1.4 on 2021-04-17 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0002_auto_20210413_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ompoaccesoriesinfo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='ompoaccesoriesinfo',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='approval_reject_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='sent_to_sample',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='status_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='submission_to_buyer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='target_ap_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
