# Generated by Django 3.1.4 on 2021-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0003_auto_20210417_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ompoaccesoriesinfo',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
