# Generated by Django 3.1.4 on 2021-04-17 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0004_ompoaccesoriesinfo_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omposampleinfo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='omposampleinfo',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='omposampleinfo',
            name='approval_reject_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='omposampleinfo',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omposampleinfo',
            name='sent_to_sample',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='omposampleinfo',
            name='status_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='omposampleinfo',
            name='submission_to_buyer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='omposampleinfo',
            name='target_ap_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
