# Generated by Django 3.1.4 on 2021-04-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0005_auto_20210417_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wopocountrydetails',
            old_name='country_id',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='wopocountrydetails',
            old_name='product_id',
            new_name='product_code',
        ),
    ]
