# Generated by Django 3.1.4 on 2021-04-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0007_auto_20210419_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='dealing_merchandiser_emp_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='factory_merchandiser_emp_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='lc_company',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='lc_company_location',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='product_cat_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='season_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='style_ref_no',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='sub_department_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='team_lead_emp_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='orderentryinfo',
            name='working_company',
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='agent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_agent_name', to='Lakshma_ERP_App.libagent'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='buyer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_buyer_name', to='Lakshma_ERP_App.libbuyer'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_client_name', to='Lakshma_ERP_App.libclient'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_company_name', to='Lakshma_ERP_App.libcompany'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='currency_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_currency_code', to='Lakshma_ERP_App.libcurrency'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_department_name', to='Lakshma_ERP_App.libdepartment'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='emp_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lin_emp_code', to='Lakshma_ERP_App.hrmemployee'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='product_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_product_cate', to='Lakshma_ERP_App.libproductcate'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='region_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_region_name', to='Lakshma_ERP_App.libregion'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='season_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_season_name', to='Lakshma_ERP_App.libseason'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='style_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_ref_no', to='Lakshma_ERP_App.libstyle'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='sub_department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_sub_department_name', to='Lakshma_ERP_App.libsubdepartment'),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='unit_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_unit_name', to='Lakshma_ERP_App.libunit'),
        ),
    ]
