# Generated by Django 3.1.4 on 2021-04-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0008_auto_20210419_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ompodetailsmaster',
            name='cpy_po_number',
        ),
        migrations.RemoveField(
            model_name='ompodetailsmaster',
            name='po_detail',
        ),
        migrations.AddField(
            model_name='ompodetailsmaster',
            name='job_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_job_no', to='Lakshma_ERP_App.wopocountrydetails'),
        ),
        migrations.AlterField(
            model_name='ompodetailsmaster',
            name='po_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_po_number', to='Lakshma_ERP_App.ompobreakdown'),
        ),
    ]
