# Generated by Django 3.1.4 on 2021-04-21 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0009_auto_20210420_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentryinfo',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_department_name', to='Lakshma_ERP_App.libdepartment'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='style_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_style_name', to='Lakshma_ERP_App.libstyle'),
        ),
        migrations.CreateModel(
            name='OmPoLabdipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no_mst', models.CharField(max_length=50)),
                ('po_no_mst_id', models.CharField(max_length=50)),
                ('po_number_mst', models.CharField(max_length=50)),
                ('lapdip_no', models.CharField(max_length=50)),
                ('target_ap_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_to_sample', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_to_buyer', models.CharField(blank=True, max_length=200, null=True)),
                ('status_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_reject_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inserted_by', models.CharField(max_length=120, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(max_length=120, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('color_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lib_labdip_color', to='Lakshma_ERP_App.libcolor')),
            ],
        ),
    ]
