# Generated by Django 3.1.4 on 2021-04-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0010_auto_20210421_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ompocolorsizebreakdown',
            name='color_number_id',
        ),
        migrations.RemoveField(
            model_name='ompocolorsizebreakdown',
            name='size_number_id',
        ),
        migrations.AddField(
            model_name='ompocolorsizebreakdown',
            name='color_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_color_name', to='Lakshma_ERP_App.libcolor'),
        ),
        migrations.AddField(
            model_name='ompocolorsizebreakdown',
            name='size_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_size_name', to='Lakshma_ERP_App.libsize'),
        ),
    ]
