# Generated by Django 3.1.4 on 2021-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lakshma_ERP_App', '0012_auto_20210422_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmemployee',
            name='inserted_by',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
